theme = "plain"
icons = "awesome"

##[icons.overrides]
volume_full = "VOL "
volume_half = "VOL "
volume_empty = "VOL "
volume_muted = "MUTE"

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GiB"
show_percentage = true
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_up = false
speed_down = false
graph_up = false
graph_down = false
interval = 1

[[block]]
block = "battery"
format = "{percentage}% {time} {power}W"
upower = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = " {Mug}/{MTg} GiB"
warning_mem = 80.0
critical_mem = 95.0
format_swap = "{SUp}%"
interval = 1

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 1
good = 50
warning = 80
format = "{average}C"

##[[block]]
##block = "load"
##interval = 1
##format = "{1m}"

[[block]]
block = "time"
interval = 1
format = "%a %m/%d/%y %r"
